### PR TITLE
turn update pin to struct

### PR DESCRIPTION
**Pull request by nik-ang**
Store the update in a struct to avoid re-obtaining for every set/reset

### CODE REVIEW

**Review by florg-32 — CHANGES_REQUESTED** [review]
This looks alright, but it then makes the TogglePin trait obsolete. Please remove it.

Also, has this been tested on hardware?

**Comment by nik-ang** [comment]
I think the TogglePin Trait is still useful since there is a mock and a non-mock TogglePin Trait, instead of a whole mock and non-moch ExecutionContext. Or did you mind something else?

This is not tested on Hardware yet but it SHOULD still work since it is just keeping the Pin inside of a struct. Because of the TogglePin trait, the rest of the code remains the same everywhere.

**Comment by florg-32** [comment]
please test the thing on the actual hardware (specifically the update pin) as this was changed

**Review by florg-32 — APPROVED** [review]

**Comment by florg-32** [comment]
Closes #71 and #78

Pls test on hardware

**Pull request merged**
